### ISSUE TITLE
Add support for query string parameters in Xero::request

### ISSUE THREAD

**Issue by adrianhardy** [picqer/xero-php-client#2]
I've forked the repo and added in support for query string parameters in `Xero::request`. The function's signature remains the same, but if `$data` contains a key `query`, it's passed to guzzle as query string parameters. 

Would you be interested in a PR?

**Comment by casperbakker** [comment]
Hi Adrian,

Absolutely. We do not use Xero very heavily anymore, but if it is a backwards compatible change, we can definitely merge it and eliminate a fork.

**Comment by casperbakker** [comment]
Thanks for the PR @adrianhardy, and sorry for the long wait.
